In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from IPython.display import display

# Optionnel pour une belle configuration des graphiques
sns.set_theme(style="darkgrid")

In [4]:
data_dir = "src/data/processed"

# Chargement transformant les Parquets en DataFrames Pandas
df_brent = pd.read_parquet(os.path.join(data_dir, "petrol_brent_daily.parquet"))
df_wti = pd.read_parquet(os.path.join(data_dir, "petrol_wti_daily.parquet"))
df_news = pd.read_parquet(os.path.join(data_dir, "petrol_news_oilprice.parquet"))

print("✅ Données chargées avec succès !")

✅ Données chargées avec succès !

In [5]:
df_brent.head()

         date   price
0  2026-04-13  123.28
1  2026-04-10  119.07
2  2026-04-09  119.03
3  2026-04-08  122.11
4  2026-04-07  138.21

In [6]:
print("--- 🛢️ Pétrole Brent ---")
# Aperçu
display(df_brent.head())
# Infos générales (types, valeurs nulles)
print("\n[INFO]")
df_brent.info()
# Statistiques descriptives
display(df_brent.describe())

--- 🛢️ Pétrole Brent ---

         date   price
0  2026-04-13  123.28
1  2026-04-10  119.07
2  2026-04-09  119.03
3  2026-04-08  122.11
4  2026-04-07  138.21

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    5000 non-null   object
 1   price   5000 non-null   object
dtypes: object(2)
memory usage: 78.2+ KB

              date  price
count         5000   5000
unique        5000   3680
top     2006-07-05  76.45
freq             1      6

In [7]:
print("--- 📰 Actualités Pétrole (Oilprice) ---")
display(df_news.head())
print("\n[INFO]")
df_news.info()

# Voir la longueur moyenne des titres s'il y a une colonne 'title' ou similaire
# display(df_news['nom_de_la_colonne'].str.len().describe())

--- 📰 Actualités Pétrole (Oilprice) ---

,date,title,content,source
0,2026-04-21,Middle East Oil Pricing Is Cracking Under Pres...,"Apr 18, 2026 at 11:09 | Alex Kimani",oilprice
1,2026-04-21,Oil Slides but the Real Test Comes This Weekend,"Apr 17, 2026 at 10:23 | Tom Kool",oilprice
2,2026-04-21,Oil Markets Reprice War Risk After Congress Re...,"Apr 16, 2026 at 17:55 | Alex Kimani",oilprice
3,2026-04-21,What’s Next for Oil Prices?,"Apr 16, 2026 at 16:35 | Tsvetana Paraskova",oilprice
4,2026-04-21,Strait of Hormuz Constraints Keep Oil Prices E...,"Apr 10, 2026 at 15:05 | Tsvetana Paraskova",oilprice

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     20 non-null     object
 1   title    20 non-null     object
 2   content  20 non-null     object
 3   source   20 non-null     object
dtypes: object(4)
memory usage: 768.0+ bytes